// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	urls "url-short/internal/repos/urls"

	mock "github.com/stretchr/testify/mock"
)

// UrlStore is an autogenerated mock type for the UrlStore type
type UrlStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, u
func (_m *UrlStore) Create(ctx context.Context, u *urls.Url) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *urls.Url) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Read provides a mock function with given fields: ctx, hash
func (_m *UrlStore) Read(ctx context.Context, hash urls.UrlHash) (*urls.Url, error) {
	ret := _m.Called(ctx, hash)

	var r0 *urls.Url
	if rf, ok := ret.Get(0).(func(context.Context, urls.UrlHash) *urls.Url); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*urls.Url)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, urls.UrlHash) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
